### ISSUE TITLE
Automatically generating a paragraph describing the analysis details

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#127]
Idea: generate a short paragraph includes the parameters and details, that could be copy and pasted into a method section of papers. 
Like, "RNA-Seq read counts data were analyzed using iDEP v0.97 [Citatoin]. Data was first filtered to remove reads not above 0.5 CPM in at least 1 sample. DESeq2 v. 2.3.3 is used to identify differentially expressed genes with FC > 1.5, FDR < 0.05. 
........"
The Phylogenetic tree software MEGA does this.

**Comment by EricTulowetzke** [comment]
@gexijin is this getting fix with the copied code? can we close this?

**Comment by bderenge** [comment]
I added a field to the pre_process object called descr. Its a string with the that reads something like "Read counts data was uploaded to iDEP v2.0 (citation). The data was filtered to include genes with more than 0.5 counts in 1 library. The data was transformed with EdgeR using a pseudocount of 4. Missing values were imputed using geneMedian."

I intend to add deg method and cutoff values to this string before this issue is closed

**Comment by gexijin** [comment]
This is a great idea!
